# Site
name: 'Rego'
description: 'Rego deals with rehabilitation information such as disease, hospital, and physical therapy'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'Rego'
email: 'rego.research@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sky:
      name:           sky
      site:           https://regoresearch.github.io
      avatar:         assets/images/sky.PNG
      bio:            "Rego 사이트를 운영하는 sky 입니다"
      email:          rego.research@gmail.com
      twitter:        #
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sky
      avatar: assets/images/sky.PNG
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
